# -----------------------------------------------------------------------------
# Air Resources Laboratory
#
# graphicsdispersion.py - 
#
# TODO - THIS IS UNFINISHED AND NEEDS TO COPY GRAPHICS GENERATION IN ashbase.py
# -----------------------------------------------------------------------------
#
#
# -----------------------------------------------------------------------------


# from abc mport ABC, abstractmethod
import datetime
import glob
import logging
import os
import shutil
import subprocess
import sys
import zipfile

import numpy as np
import requests
import xarray as xr

from utilvolc.runhelper import Helper
from ashapp.filenamer import  JobFileNameComposer
from ashapp.ashruninterface import ModelOutputInterface
import ashapp.plotting_functions as plotf
from utilhysplit.evaluation import web_ensemble_plots as wep
from monetio.models import hysplit
from ashapp.cdump2xml import HysplitKml

logger = logging.getLogger(__name__)


# create_maptext
# get_maptext_info
# generate_kmz
# create_zipped_up_file



class GraphicsTrajectory(ModelOutputInterface):
    ilist = [("WORK_DIR",'req'),
             ("jobid",'req'),
             ("jobname",'req'),
             ("MAP_DIR",'req'),
             ("HYSPLIT_DIR",'req'),
             ("mapBackground",'req'),
             ('graphicsResolution','req'),
             ("CONVERT_EXE",'req'),
             ('zip_compression_level','req')]


    def __init__(self,inp):
        self._inputlist = []
        self._outputlist = []
        self._fhash = {}
        self.inp = inp
        self.filelocator = inp
        #self._ncfile = ashnetcdf.HYSPLITAshNetcdf('TEMP')
        self._ncfile = None

    def ingest_model_output(self, modeloutput):
        """ modeloutput - class with ModelOutputInterface as base class
        """
        self.inputlist = modeloutput.outputlist
        self._ncfile = modeloutput._ncfile
    
    #def load_ncfile(self,ncfile):
    #    self._ncfile = ashnetcdf.HYSPLITAshNetcdf(self._fhash['xrfile'])
    #    #self._ncfile = ncfile

    @property
    def ncfile(self):
        return self._ncfile

    @property
    def inputlist(self):
        return self._inputlist

    @inputlist.setter
    def inputlist(self, inlist):
        self._inputlist = inlist 

    # no setter
    @property
    def outputlist(self):
        outputlist = []
        return self._outputlist

    def _get_filenames(self):
        fhash = {}
        # input files
        fhash['tdump'] = self.filelocator.get_tdump_filename()
        # output files
        ptype = 'ps'
        # could use html or svg for svg files
        fhash['trajplot'] = self.filelocator.get_trajplot_filename(ptype=ptype)
        fhash['kml'] = self.filelocator.get_trajplot_kml_filename()
        fhash['kmz'] = self.filelocator.get_kmz_filename()
        fhash['gis_status'] = self.filelocator.get_gis_status_filename()
        #TODO
        # create montage
        # create allplots.pdf
        # create awips2 netcdf files
        # create massloading kmz file
        # GELABEL files?
        # zip files

        return fhash       
 

    def check(self):
       rval = True
       for filename in self._outputlist:
           if not os.path.isfile(filename):
              return False
       return True

    def postprocess(self):
        #stage=0
        # create the trajectory plot
        tdump_filename = self._fhash['tdump']
        trajplotname = self._fhash['trajplot']
        print('trajplot', trajplotname)
        gis_status_file = self._fhash['gis_status'] 
        stage=0
        plotf.create_trajectory_plot(self.inp, tdump_filename, trajplotname,stage,gis_status_file)
        self.create_kmz() 
        #create_concentration_montage(stage=stage) 
        #make_awips_netcdf()
        return True

    #def load_netcdf(self):
    #    if os.path.isfile(self._fhash['xrfile']):
    #       temp = xr.open_dataset(self._fhash['xrfile'])
    #       self._ncinput = temp[list(temp.data_vars.keys())[0]]
    #    else:
    #       logger.warning('could not find {}'.format(self._fhash['xrfile'])) 

    def create_kmz(self):
        # the kml file is generated by trajplot with the -a3 option.
        jobid = self.inp['jobid']
        hdir = self.inp['HYSPLIT_DIR']
        compresslevel = self.inp['zip_compression_level']
        kmlfilename = self._fhash['kml']
        kmzfilename = self._fhash['kmz']
        plotf.generate_kmz(hdir,[kmlfilename],kmzfilename,compresslevel)

    @property
    def filelocator(self):
        #self._filelist = list(set(self._filelist))
        return self._filelocator

    @filelocator.setter
    def filelocator(self, finp):
        """
        input dictionary  with WORK_DIR, jobid, jobname
        or MetFileFinder object.
        """
        if isinstance(finp, dict):
            self._filelocator = JobFileNameComposer(
                finp["WORK_DIR"], finp["jobid"], finp["jobname"]
            )
            # get all the filenames here.
            self._fhash = self._get_filenames()
        else:
            # TO DO? add test for type.
            self._filelocator = finp
        # after the filelocator is set, need to redo the filenames
        # self._get_filenames()

